
HTTP_RETURN_CODE_SUCCESS_ADDED: int = 200
HTTP_RETURN_CODE_SUCCESS_NOTHING_TO_DO: int = 204
HTTP_RETURN_CODE_NO_CONNECTION_TO_SEEK: int = 404
HTTP_RETURN_CODE_MALFORMED_REQUEST: int = 405
HTTP_RETURN_CODE_NO_CONNECTION_TO_FILE_DOWNLOAD: int = 502
