@startuml

title: MaSeMiWa\nINSERT-Procedure
header version: %date("dd.MM.yyyy")

skinparam shadowing false


!define     info(text)      #fff:text}
!definelong stoperror(text)
    #faa:text;
    stop
!enddefinelong
!definelong stopsuccess(text)
    #afa:text;
    stop
!enddefinelong
!definelong file_failed()
    :log reason;
    info(continue)
    detach
!enddefinelong

start

info(file link known)

if (fetch metadate for ID) then (error)
    stoperror(Return 404)

else (success)
    repeat :iterate over ""content_blobs"";
        if (check MIME in allow list) then (no)
            file_failed()
        else (yes)
            if (Download file) then (failed)
                file_failed()
            else (success)
                if (validate XML) then (invalid)
                    file_failed()
                else (valid)
                    if (validate namespace) then (invalid)
                        file_failed()
                    else (valid)
                        if (send INSERT to Morre) then (failed)
                            file_failed()
                        else (success)
                            :log "imported model xyz";
                            :break}
                            detach
                        endif
                    endif
                endif
            endif
        endif
    repeat while (next item?)

    if (s.th. was imported?) then (yes)
        stopsuccess(Return 200)
    else (no)
        stoperror(Return 400)

endif


@enduml