@startuml

title: MaSeMiWa\nINSERT-Procedure
header version: %date("dd.MM.yyyy")

skinparam shadowing false


!define     info(text)      #fff:text}
!definelong stoperror(text)
    #faa:text;
    stop
!enddefinelong
!definelong stopsuccess(text)
    #afa:text;
    stop
!enddefinelong
!definelong file_failed()
''    :log;
''    info(continue)
''    detach
!enddefinelong

start

info(file link known)

if (fetch metadata for ID) then (error)
    stoperror(Return 404)

else (success)
    repeat :iterate over ""content_blobs"";
        if (check MIME in allow list) then (no)
            file_failed()
        elseif (Download file) then (failed)
            file_failed()
        elseif (validate XML) then (invalid)
            file_failed()
        elseif (validate namespace\nand level/version) then (invalid)
            file_failed()
        else (success)
            #afa:add to Queue;
''            :log "imported model xyz";
        endif
        
        :log;
        
    repeat while (next item?)

    if (s.th. was added to Queue?) then (yes)
        stopsuccess(Return 200)
    else (no)
        stoperror(Return 400)

endif


@enduml