@startuml

title MaSiMiWa - Sequence Overview\nfor a valid request
header version: %date("dd.MM.yyyy")
'header version: 23.11.2018

skinparam defaultFontName Helvetica
skinparam shadowing false


!definelong check_logic()
group #fda check logic<sup>(//see activity UML//)</sup>

seek            <-      miwa            : get json
seek            -->     miwa

miwa            ->]                     : OPT: get content_blob (files)
miwa            <--]

end
!enddefinelong

!definelong process_queue()
miwa            -->     miwa            : process queue

    activate miwa

    loop #efe queue
    
    loop #ffe insert each content

    miwa            ->      morre           : ""add_model""
        activate morre
        
        morre           ->]                     : get file from the Internet
        morre           <--]

        morre           ->      db              : insert new model
            activate db
        morre           <--     db              : SUCCESS
            deactivate db
        
    miwa            <--     morre           : SUCCESS
        deactivate morre
    
    end
    end

    miwa            ->      morre           : ""create_annotation_index""\nupgrade annotations, etc.\n//for the whole DB//
        activate morre

        loop #efe annotations

        morre           ->]                     : get data from the Internet
        morre           <--]

        morre           ->      db              : insert additional data
            activate db
        morre           <--     db              : SUCCESS
            deactivate db
        
        end
    
    miwa            <--     morre           : SUCCESS
        deactivate morre 

    deactivate miwa
!enddefinelong







participant "SEEK" as seek
box "MaSyMoS"
    control "MaSiMiWa" as miwa
    control "MaSyMoS-Morre" as morre
    database "masymos_neo4j_database" as db


activate seek #aaf
    activate miwa #afa

== INSERT ==

hnote over seek
    * user added a public model
    * user made a model public
end note

seek            ->      miwa            : insert_model(id)
    activate miwa

check_logic()

seek            <--     miwa            : SUCCESS
    deactivate miwa

process_queue()







== DELETE ==

hnote over seek
    * user deleted a public model
    * user made a public model non-public
end note

seek            ->      miwa            : delete_model(id)
    activate miwa
    
    miwa            ->      morre           : ""delete_model""
        activate morre
    
        morre           ->      db              : delete model
            activate db
        morre           <--     db              : SUCCESS
            deactivate db

    miwa            <--     morre           : SUCCESS
        deactivate morre 

seek            <-      miwa            : SUCCESS
    deactivate miwa 






== UPDATE ==

hnote over seek
    * user uploads a new version
       to a public model
end note

seek            ->      miwa            : update_model(id)
    activate miwa

    note over miwa,db #fff
        # do a DELETE
        # do an INSERT
    end note

seek            <-      miwa            : SUCCESS
    deactivate miwa 




== BATCH ==

hnote over seek
    * admin forces recreation of masymos-db
    * can take several hours
    * data is not usable before annotating is done,
       so wait with the SUCCESS until finished
end note


seek            ->      miwa            : insert_models(id<<List>>)
activate miwa

loop list
check_logic()
end

miwa            ->      morre           : delete whole database
    activate morre
    morre           ->      db              : delete whole database
        activate db
    morre           <--     db
        deactivate db
miwa            <--     morre           : SUCCESS
    deactivate morre

seek            <--     miwa            : SUCCESS
deactivate miwa

process_queue()





@enduml
